name: conda-smithy
channels:
  - conda-forge
  - nodefaults
dependencies:
  - python>=3.6
  # Development dependencies
  - pip
  - python-build
  - setuptools>=45
  - setuptools_scm>=7
  - tomli>=1.0.0
  - pre-commit
  - mock
  - pytest
  - pytest-cov
  # Runtime dependencies
  - conda >=4.2
  - conda-build >=3.21.8
  - conda-package-handling >=1.9.0
  - jinja2
  - requests
  - pycryptodome
  - gitpython
  - pygithub >=2,<3
  - ruamel.yaml
  - conda-forge-pinning
  - vsts-python-api
  - toolz
  - shellcheck
  - scrypt
  - license-expression
  - libarchive
  - cirun >=0.30
  - pydantic >=2,<3
  - jsonschema
  - backports.strenum
  - exceptiongroup
  - rattler-build-conda-compat >0.0.3
