name: conda-smithy
channels:
  - conda-forge
  - nodefaults
dependencies:
  - python>=3.6
  # Development dependencies
  - pip
  - python-build
  - setuptools>=45
  - setuptools_scm>=7
  - tomli>=1.0.0
  - pre-commit
  - mock
  - pytest
  - pytest-cov
  # Runtime dependencies, duplicated in conda_smithy.recipe/meta.yaml
  - conda >=4.2
  - conda-build >=3.18.3
  - conda-package-handling >=1.9.0
  - jinja2
  - requests
  - pycryptodome
  - gitpython
  - pygithub <2
  - ruamel.yaml
  - conda-forge-pinning
  - vsts-python-api
  - toolz
  - shellcheck
  - scrypt
  - license-expression
  - libarchive
